- name: Perform full system upgrade
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
    update_cache: true

- name: Clean up orphaned packages
  ansible.builtin.apt:
    autoremove: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if necessary
  ansible.builtin.reboot:
    reboot_timeout: 300
    test_command: uptime
  when: reboot_required.stat.exists
