- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: true

- name: Enable automatic security updates
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

- name: Ensure unattended-upgrades config is set
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: '^//Unattended-Upgrade::Mail'
    line: 'Unattended-Upgrade::Mail "root";'
    state: present
    create: true
    mode: '0644'

- name: Perform full system upgrade
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
    update_cache: true

- name: Clean up orphaned packages
  ansible.builtin.apt:
    autoremove: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if necessary
  ansible.builtin.reboot:
    reboot_timeout: 300
    test_command: uptime
  when: reboot_required.stat.exists
