- name: Perform full system upgrade
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
    update_cache: true

- name: Clean up orphaned packages
  ansible.builtin.apt:
    autoremove: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required


- name: Reboot if necessary
  ansible.builtin.reboot:
    reboot_timeout: 300
    test_command: uptime
  when: reboot_required.stat.exists

- name: Clean APT cache
  ansible.builtin.apt:
    autoclean: true

- name: Prune Docker unused images, containers, and volumes
  community.docker.docker_prune:
    images: true
    containers: true
    volumes: true
    networks: true
  when: ansible_facts.packages is defined and 'docker' in ansible_facts.packages

- name: Vacuum old journal logs older than 7 days
  ansible.builtin.command: journalctl --vacuum-time=7d
  become: true
  changed_when: false

- name: Remove old log files in /var/log older than 30 days
  ansible.builtin.find:
    paths: /var/log
    age: 30d
    recurse: true
  register: old_logs

- name: Delete old log files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_logs.files }}"
  when: old_logs.matched > 0
