---
all:
  hosts:
    netprobe01.tail294b9a.ts.net: {}
    netprobe02.tail294b9a.ts.net: {}
    netprobe03.tail294b9a.ts.net: {}
    netprobe04.tail294b9a.ts.net: {}
    netprobe05.tail294b9a.ts.net: {}
    netprobe06.tail294b9a.ts.net: {}
    netprobe07.tail294b9a.ts.net: {}
    netprobe10.tail294b9a.ts.net: {}
    netprobe11.tail294b9a.ts.net: {}
    netprobe12.tail294b9a.ts.net: {}
    netprobe13.tail294b9a.ts.net: {}
    netprobe14.tail294b9a.ts.net: {}
    netprobe15.tail294b9a.ts.net: {}
    netprobe16.tail294b9a.ts.net: {}
    cpe-srv.tail294b9a.ts.net: {}
