all:
  children:
    # Group for Docker installation
    docker_hosts:
      hosts:
        host1.ts.net:
        host2.ts.net:

    # Group for Prometheus exporters & Telegraf
    monitoring_hosts:
      hosts:
        host1.ts.net:
        host3.ts.net:

    # Group for Tailscale VPN enrollment
    vpn_hosts:
      hosts:
        host1.ts.net:
        host2.ts.net:
        host3.ts.net: