node_exporter_url: >-
  https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/
  node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}.tar.gz
  