---
- name: Stop Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: stopped

- name: Disable Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: false

- name: Remove Node Exporter systemd unit file
  ansible.builtin.file:
    path: /etc/systemd/system/node_exporter.service
    state: absent

- name: Remove Node Exporter binary
  ansible.builtin.file:
    path: /usr/local/bin/node_exporter
    state: absent

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Remove node_exporter user
  ansible.builtin.user:
    name: node_exporter
    state: absent
    remove: true

- name: Remove node_exporter group
  ansible.builtin.group:
    name: node_exporter
    state: absent
