- name: Check if Speedtest CLI is already installed
  ansible.builtin.command: which speedtest
  register: speedtest_check
  changed_when: false
  failed_when: false

- name: Skip Speedtest install — already installed
  ansible.builtin.meta: end_host
  when: speedtest_check.rc == 0

- name: Add Ookla Speedtest repo (via packagecloud script)
  ansible.builtin.shell: |
    set -o pipefail
    curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash
  args:
    executable: /bin/bash
  register: speedtest_repo
  changed_when: "'The repository is already configured' not in speedtest_repo.stdout"

- name: Install Speedtest CLI
  ansible.builtin.apt:
    name: speedtest
    state: present
