---
- name: Verify Docker installation
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Docker version
      command: docker --version
      register: docker_version
      changed_when: false
    - name: Assert Docker is installed
      assert:
        that:
          - docker_version.rc == 0 