#SPDX-License-Identifier: MIT-0
---
- name: Check if 'docker' systemd service is running
  ansible.builtin.systemd:
    name: docker
  register: docker_service
  changed_when: false
  failed_when: false

- name: Skip Docker Setup
  ansible.builtin.meta: end_host
  when: docker_service.status.ActiveState == "active"

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_installed
  failed_when: false
  changed_when: false

- name: Install required packages for Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
  when: docker_installed.rc != 0

- name: Add Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_apt_gpg_key }}"
    dest: "/usr/share/keyrings/docker-archive-keyring.gpg"
    mode: '0644'
  when: docker_installed.rc != 0

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
      {{ docker_apt_repo }}
      {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  when: docker_installed.rc != 0

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true
  when: docker_installed.rc != 0

- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Add users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_group_users }}"
  notify: Restart docker

