- name: Stop Docker service
  ansible.builtin.systemd:
    name: docker
    state: stopped

- name: Disable Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: false

- name: Remove Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: absent
    purge: true
    autoremove: true

- name: Remove Docker group
  ansible.builtin.group:
    name: docker
    state: absent

- name: Autoremove unused packages
  ansible.builtin.apt:
    autoremove: true
    autoclean: true
