# The beszel ssh key should be stored in an encrypted vault:
# Create group_vars/beszel_hosts/vault.yml with:
# beszel_agent_ssh_key: 'ssh-ed25519 lalalal'

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Download the install-agent.sh script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
    dest: /tmp/install-agent.sh
    mode: '0755' # Set executable permissions

- name: Remove beszel agent if service exists
  become: true
  ansible.builtin.command:
    cmd: /tmp/install-agent.sh -u
  when: ansible_facts.services['beszel-agent.service'] is defined
  changed_when: false

- name: Run the install-agent.sh script with auto-update
  ansible.builtin.shell: |
    set -o pipefail && yes | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
  args:
    executable: /bin/bash
  when: beszel_agent_autoupdate | bool
  ignore_errors: false
  changed_when: false

- name: Run the install-agent.sh script without auto-update
  ansible.builtin.shell: |
    set -o pipefail && yes N | /tmp/install-agent.sh -p {{ beszel_agent_ssh_port }} -k "{{ beszel_agent_ssh_key }}"
  args:
    executable: /bin/bash
  when: not beszel_agent_autoupdate | bool
  ignore_errors: false
  changed_when: false
