- name: Remove beszel-agent if service exists
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Download install-agent.sh script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/henrygd/beszel/main/supplemental/scripts/install-agent.sh
        dest: /tmp/install-agent.sh
        mode: '0755' # Set executable permissions
      when: ansible_facts['services']['beszel-agent.service'] is defined

    - name: Remove beszel agent
      become: true
      ansible.builtin.command:
        cmd: /tmp/install-agent.sh -u
      when: ansible_facts['services']['beszel-agent.service'] is defined
      changed_when: false
