---
# Deploy the Beszel Agent to all hosts. Requires beszel_agent_ssh_key in group_vars/all/vault.yml.
- name: Deploy Beszel Agent
  hosts: all
  gather_facts: true
  vars_files:
    - ../group_vars/all/vault.yml
  become: true
  roles:
    - beszel-agent
