- name: Check if 'telegraf' systemd service is running
  ansible.builtin.systemd:
    name: telegraf
  register: telegraf_service
  changed_when: false
  failed_when: false

- name: Skip Telegraf setup
  ansible.builtin.meta: end_host
  when: telegraf_service.status.ActiveState == "active"

- name: Add InfluxData GPG key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present

- name: Add InfluxData APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://repos.influxdata.com/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install telegraf
  ansible.builtin.apt:
    name: telegraf
    state: present
    update_cache: true
  notify: Restart telegraf

- name: Ensure telegraf is running
  ansible.builtin.systemd:
    name: telegraf
    enabled: true
    state: started
