---
# yamllint disable rule:truthy
name: Ansible Lint
on:
  push:
    branches: ["master"]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  lint:
    name: Lint & Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint molecule[docker]

      - name: Run ansible-lint
        run: |
          ansible-lint .
