# .github/workflows/ansible-lint.yml
name: Ansible Lint

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.4.0
        # optional (see below):
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""
