---
# yamllint disable rule:truthy
name: Ansible Lint, Syntax Check & Molecule

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  lint:
    name: Lint & Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and linters
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint molecule[docker]

      - name: Run ansible-lint
        run: |
          ansible-lint .

  molecule:
    name: Molecule Test (docker role)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible, Molecule, and Docker
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule[docker]

      - name: Run Molecule tests for docker role
        run: |
          cd roles/docker && molecule test